# Generated by Django 3.1.4 on 2020-12-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='columns',
            old_name='schema_id',
            new_name='schema',
        ),
        migrations.RenameField(
            model_name='schema',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='schema',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
