# Generated by Django 3.1.4 on 2020-12-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20201215_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Columns',
            new_name='Column',
        ),
    ]
