# Generated by Django 3.1.4 on 2020-12-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20201216_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='string_separator',
        ),
        migrations.AddField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote(")'), ("'", "Single-quote(')")], default=',', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma(,)'), (';', 'Semicolon(;)')], max_length=2),
        ),
    ]
