# Generated by Django 3.1.4 on 2020-12-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20201216_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], max_length=2),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote (")'), ("'", "Single-quote (')")], max_length=2),
        ),
    ]
