# Generated by Django 3.1.4 on 2020-12-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready'), (1, 'Processing...')]),
        ),
    ]
